// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "lobby_player.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message LobbyPlayer
 */
export interface LobbyPlayer {
	/**
	 * @generated from protobuf field: uint64 id = 1
	 */
	id: bigint;
	/**
	 * @generated from protobuf field: string username = 2
	 */
	username: string;
	/**
	 * @generated from protobuf field: string role = 3
	 */
	role: string;
	/**
	 * @generated from protobuf field: uint32 task_force = 4
	 */
	taskForce: number;
	/**
	 * @generated from protobuf field: string selected_champion = 5
	 */
	selectedChampion: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class LobbyPlayer$Type extends MessageType<LobbyPlayer> {
	constructor() {
		super("LobbyPlayer", [
			{ no: 1, name: "id", kind: "scalar", T: 4, /*ScalarType.UINT64*/ L: 0 /*LongType.BIGINT*/ },
			{ no: 2, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 3, name: "role", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
			{ no: 4, name: "task_force", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
			{ no: 5, name: "selected_champion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
		]);
	}
	create(value?: PartialMessage<LobbyPlayer>): LobbyPlayer {
		const message = globalThis.Object.create(this.messagePrototype!);
		message.id = 0n;
		message.username = "";
		message.role = "";
		message.taskForce = 0;
		message.selectedChampion = "";
		if (value !== undefined) {
			reflectionMergePartial<LobbyPlayer>(this, message, value);
		}
		return message;
	}
	internalBinaryRead(
		reader: IBinaryReader,
		length: number,
		options: BinaryReadOptions,
		target?: LobbyPlayer,
	): LobbyPlayer {
		let message = target ?? this.create(), end = reader.pos + length;
		while (reader.pos < end) {
			let [fieldNo, wireType] = reader.tag();
			switch (fieldNo) {
				case /* uint64 id */ 1:
					message.id = reader.uint64().toBigInt();
					break;
				case /* string username */ 2:
					message.username = reader.string();
					break;
				case /* string role */ 3:
					message.role = reader.string();
					break;
				case /* uint32 task_force */ 4:
					message.taskForce = reader.uint32();
					break;
				case /* string selected_champion */ 5:
					message.selectedChampion = reader.string();
					break;
				default:
					let u = options.readUnknownField;
					if (u === "throw") {
						throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
					}
					let d = reader.skip(wireType);
					if (u !== false) {
						(u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
					}
			}
		}
		return message;
	}
	internalBinaryWrite(message: LobbyPlayer, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
		/* uint64 id = 1; */
		if (message.id !== 0n) {
			writer.tag(1, WireType.Varint).uint64(message.id);
		}
		/* string username = 2; */
		if (message.username !== "") {
			writer.tag(2, WireType.LengthDelimited).string(message.username);
		}
		/* string role = 3; */
		if (message.role !== "") {
			writer.tag(3, WireType.LengthDelimited).string(message.role);
		}
		/* uint32 task_force = 4; */
		if (message.taskForce !== 0) {
			writer.tag(4, WireType.Varint).uint32(message.taskForce);
		}
		/* string selected_champion = 5; */
		if (message.selectedChampion !== "") {
			writer.tag(5, WireType.LengthDelimited).string(message.selectedChampion);
		}
		let u = options.writeUnknownFields;
		if (u !== false) {
			(u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
		}
		return writer;
	}
}
/**
 * @generated MessageType for protobuf message LobbyPlayer
 */
export const LobbyPlayer = new LobbyPlayer$Type();
