// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "lobby_host_service.proto" (syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service LobbyHostService
 */
export const LobbyHostService = new ServiceType("LobbyHostService", []);
