// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "lobby_host_service.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { LobbyHostService } from "./lobby_host_service";
/**
 * @generated from protobuf service LobbyHostService
 */
export interface ILobbyHostServiceClient {
}
/**
 * @generated from protobuf service LobbyHostService
 */
export class LobbyHostServiceClient implements ILobbyHostServiceClient, ServiceInfo {
	typeName = LobbyHostService.typeName;
	methods = LobbyHostService.methods;
	options = LobbyHostService.options;
	constructor(private readonly _transport: RpcTransport) {
	}
}
